export  class CommonConstants {
  /**
   * Component size.
   */
  static readonly FULL_PERCENT: string = '100%';
  static readonly FULL_SIZE: string ='100%'
  static readonly FULL_HEIGHT: string = '100%';
  static readonly FULL_WIDTH: string = '100%';

  //opacity
  static readonly FULL_OPACITY: number =1;
  static readonly SIXTY_OPACITY: number =0.6;
  static readonly EIGHTY_OPACITY: number = 0.8;

  //fornt weight
  static readonly FONT_WEIGHT_FIVE:  number = 500;
  static readonly FONT_WEIGHT_SEVEN: number = 700;
  static readonly FONT_WEIGHT_FOUR:  number = 400;

  /**
   * Component height percentage: 60%.
   */
  static readonly SIXTY_HEIGHT: string = '60%';

  static readonly IMAGE_ASPECT_RATIO: number = 2.25;

  /**
   * Text line value: 2.
   */
  static readonly TWO_TEXT_LINE: number = 2;


  /**
   * vp_xxx:
   */
  static readonly  VP_FOURTEEN="14vp"

  static readonly TWELVE_SPACE: number = 12

  /**
   * IndexPage tab...index
   */
  static readonly INDEX_PAGE="indexPage";

  static readonly  BTN_NAVIGATION_SPACE: string = '6vp';

  /**
   * Login token
   */
  static readonly LOGIN_AUTH="auth";

  /**
   * url base
   */
  static readonly BASE_URL="http://192.168.3.56:8000"
}